import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CustomNavbar } from "@/components/layouts/CustomNavbar";
import { CustomFooter } from "@/components/layouts/CustomFooter";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomNavbar/>
        <div className="container">{children}</div>
        <CustomFooter className="mt-auto" />
      </body>
    </html>
  );
}
